name: Notify Slack - Discussions

on:
  discussion:
    types: [created]

permissions: {}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send discussion notification to Slack
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_DISCUSSION }}
          webhook-type: incoming-webhook
          payload: |
            {
              "action": "${{ github.event.action }}",
              "discussion_url": "${{ github.event.discussion.html_url }}",
              "package_name": "${{ github.repository }}"
            }
